### ISSUE TITLE
Stream deck doesn't show companion buttons 

### ISSUE THREAD

**Issue by paintyou** [bitfocus/companion-module-bitfocus-companion#12]
I'm on a Mac. I installed the ATEM software, the Stream Deck software and then the Companion software. I selected Blackmagic ATEM in the instances panel, added the ip address of my Atem and the status read OK. I installed some preset buttons for my PTZ Optics cameras and they work perfectly on the emulator, but my Stream Deck doesn't display the buttons, only the Elgato logo is lit up on the center button. I have tried numerous times. Uninstalled and reinstalled everything, but to no avail. Is this a bug or am I missing something. I followed the video by John Barker step by step but to no avail.

**Comment by amckean** [comment]
I have the same problem. This bug was supposedly fixed in 2.0 but I see it in 2.1.0.

**Comment by rontomasch** [comment]
Same here! The only buttons that show up on my stream deck are the vmix shortcuts that I install.

**Comment by rontomasch** [comment]
I believe I found the solution. In the Bitfocus companion software, click on the surfaces tab. Mine had, Elgato Streamdeck Emulator & Elgato Streamdeck Plugin. What was missing was the Elgato Streamdeck device, Make sure the stream deck software is closed. Go to the system tray and right click on the stream deck software icon and click on, "Quit Stream Deck". Now go back to the surfaces tab in companion software and click, "Rescan USB". This should appear;  Under the "ID" should be a series of numbers and under "Type" should be listed, "Elgato Streamdeck Device". Once these things appeared I was able to load all the shortcuts I wanted both from vMix and Blackmagic Design ATEM mini Pro. Everything works as expected now.

**Comment by ThatAVGuy** [comment]
So once you had the stream deck appear on the companion software... did you leave companion running and then open up the stream deck software? If so what were your next steps to get companion buttons into stream deck software?

**Comment by McHauge** [comment]
@ThatAVGuy, the preferred way is to ONLY use one software at a time, so either companion or Elgato's software, and not both. But if you have to use both, install the Bitfocus Companion plugin (found in the elgato store) and run both at the same time.

**Comment by Julusian** [comment]
It sounds like this has been resolved. If not then please open a new issue in the correct repository https://github.com/bitfocus/companion
