### ISSUE TITLE
[BUG] Instance status feedback is broken

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-bitfocus-companion#15]
**Describe the bug**

When you try to use the internal instance status feedback module, there is no options to select which instance you want to track, or what colors to change.

**Comment by krocheck** [comment]
Not sure if its working as intended, but the description for the feedback is: `If any companion instance encounters any errors, this will turn red`.  The processing code is:
```javascript
	if (feedback.type == 'instance_status') {

		if (self.instance_errors > 0) {
			return {
				color: self.rgb(255,255,255),
				bgcolor: self.rgb(200,0,0)
			};
		}

		if (self.instance_warns > 0) {
			return {
				color: self.rgb(0,0,0),
				bgcolor: self.rgb(255,255,0)
			};
		}

		return {
			color: self.rgb(255,255,255),
			bgcolor: self.rgb(0,200,0)
		};
	}
```
As implemented the label doesn't match the actual function of the feedback.
