### ISSUE TITLE
unable to create account- I get validation error

### ISSUE THREAD

**Issue by kitabug124** [bitfocus/companion-module-bitfocus-companion#24]
I have tried to create an account for bitfocus.io but I get this message over and over:  Error creating account.  Please try again later.  Validation error

I don't see that I am doing anything wrong, and  I have tried over multiple days.  Can you help?

-Bill
![error](https://user-images.githubusercontent.com/76751205/103311502-89519e80-49e8-11eb-89ec-f84a82f09705.jpg)

**Comment by Julusian** [comment]
If you are still having this problem, please email support@bitfocus.io
This repository is for a component of companion, not the website
