### ISSUE TITLE
Actions should default to 'this page' and 'this button'

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-bitfocus-companion#26]
The default page & button of the actions should be itself, not 1,1.
This will be a much more sensible default as it will likely be wanted instead of pointing at what is by default a page up button on a different page

**Comment by istnv** [comment]
'This page/button' is a new feature added a few days ago. I can add those defaults to the current open PR #25.

**Comment by istnv** [comment]
@Julusian A side-effect of adding 'This page'  to `CHOICES_PAGES`:
https://github.com/bitfocus/companion-module-bitfocus-companion/blob/7a84df70064e8a3907ecbff5ea66359885d4a58b/index.js#L294

`'set_page'` now has the option to go to itself (a do-nothing action).

**Comment by Julusian** [comment]
True, so it does make sense to have then. Maybe not as the default on that action though

**Comment by istnv** [comment]
They default to page 1 in this PR
