### ISSUE TITLE
2.1.2 javascript error on vmix (22) startup

### ISSUE THREAD

**Issue by rom1ferre** [bitfocus/companion-module-bitfocus-companion#28]
Hello, since I've upgraded to version 2.1.2, Companion is no longer starting properly if vmix is open.
i've tried to reset configuration and re-import but same result.
the inputs in vmix have not been changed so i don't understand help please !
my show is in two days !
![Capture companion](https://user-images.githubusercontent.com/78033100/105861262-d24c4100-5fee-11eb-8f30-a07bda5048c2.PNG)

**Comment by McHauge** [comment]
Hi would you mind checking if this problem still orcures in the newest beta, also could you post a .txt file or .xml file with the content of the vmix web interface and adding a /api at the end

**Comment by rom1ferre** [comment]
Hi McHauge, I am a beginner so I don't know where to find latest beta and how do I copy the content of the vmix web interface ?
Sorry for my ignorance...

**Comment by McHauge** [comment]
click the little builds button
![image](https://user-images.githubusercontent.com/31018035/105864612-68ce3180-5ff2-11eb-9be3-bb3dde36698b.png)

**Comment by rom1ferre** [comment]
Ok I've installed version companion-2.2.0-03c9a37-2813-win64.exe
javascript error solved, thank's a lot !
Still don't have color feedback on buttons but It is not a major pb, I already had this pb with previous version 2.1.0

**Comment by McHauge** [comment]
Do you happen to have a list as an input without any things in it, also what version of vmix?

**Comment by rom1ferre** [comment]
Yes I had an empty list because I’ve moved my pictures...

Romain Ferré
