### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-module-bitfocus-companion#36]
There has been no reason to create a valid `HELP.md` file because this module does not display in the list with the other instances.
Recently, a lot of features have been added with no place to properly document them.
I would suggest creating a current `HELP.md` file and providing access to that via the GUI sidebar or some way to include the file into the Getting Started documentation.

**Comment by McHauge** [comment]
This module is partly documented in the main getting started guide, as it provides the internal stuff lays out in that guide

**Comment by istnv** [comment]
@McHauge I am aware of that. 
Would it be easier to maintain as part of the module itself, then merge into the getting started page?

**Comment by Julusian** [comment]
I think @krocheck was thinking about merging this repository into the core one, which would make it easier to maintain as part of getting started

**Comment by krocheck** [comment]
yeah, v2.3 is going to move this into the core, so documenting within `gettingstarted.md` is the best move.

**Comment by istnv** [comment]
Thanks all! I just finished adding some requested features and was looking for the best place to add documentation.
