### ISSUE TITLE
Delay when loading pages

### ISSUE THREAD

**Issue by imh248** [bitfocus/companion-module-bitfocus-companion#37]
Hello, My name is Ian and I'm a Venue Space Technician at Facebook. Our events team started using StreamDeck XLs to control functions on vMix software that lives on AWS instances via PC over IP (Teradici). We recognize potential for delay with all these jumps in the workflow, but sending commands doesn't seem to be an issue. The issue we're seeing is when it comes to switching pages it takes about 5 seconds to load. This compounds when you need to scroll 2-3 pages. Is there anything we can try to do to lower the time it takes to load pages, or is this delay normal operation?

https://user-images.githubusercontent.com/84591355/119182306-bd356b00-ba40-11eb-9da5-3a0f3282db2b.mp4

Thank you.

Sorry if this isn't the right place to report this. I've previously submitted a ticket through the Bitfocus support page, but never received a response. It also says I'm unable to sign in on a suspended account to the website, even though I just recently created it.

**Comment by McHauge** [comment]
where do you have Companion running, local or on the AWS?

**Comment by imh248** [comment]
it's running on the AWS instance.

**Comment by McHauge** [comment]
that's probably why personally I would try and run companion local and point it to the remote vMix server. that way you don't have to have the graphical data and only the commands going the long way around.

**Comment by imh248** [comment]
ok i'll give that a whirl this week. Thank you!
