### ISSUE TITLE
[REWORK] Consider moving "custom_variable" functionality to own unit

### ISSUE THREAD

**Issue by abebeos** [bitfocus/companion-module-bitfocus-companion#53]
(draft, text is updated)

## Requriements

* stay backwards compatible
  * allow for automated migrations
  * last resort: manual migration, deprecation notice
* ~rewrite related (see  [comment](https://github.com/bitfocus/companion-module-bitfocus-companion/issues/53#issuecomment-1046042258)~
  * ~"replace the prototype classes with proper classes"~
  * ~"remove all the system.emit and system.on calls, and make them be normal method calls"~

## Structure

* custom-variable related code belongs into to `companion/lib/variable.js`
* custom-variable related actions belong into `companion-module-bitfocus-customvar` (a core-module)
* `companion-module-bitfocus-companion` imports/uses functionality as needed

## Process

In order to achieve near 100% backwards-compatibility:
- [x] duplicate the existent bitfocus-companion code to bitfocus-customvar
- [x] remove all code not related to the variables
- ~start refactoring (negate `prototype`, `system.emit`, `system.on`~
- [ ] provide migration
- [ ] delete customvar related code from bitfocus-companion

## Repo

https://github.com/abebeos/companion-module-bitfocus-customvar

## Background

During my work on https://github.com/bitfocus/companion-module-generic-http/pull/28, I got more and more the feeling that `custom_variable` related functionality like

https://github.com/bitfocus/companion-module-bitfocus-companion/blob/master/index.js#L796-L864

should be better moved to an own module.

~I'm not fully confident about this proposed change (technical internals), but~ from a user perspective, it becomes quite clear a `must-have`:

## Status

The companion-ui `Set actions` shows a drop-down like this

![image](https://user-images.githubusercontent.com/84547391/154559752-1fe96fa3-73c1-44a0-a141-acd57ee98c55.png)

## Expected

Moving the custom-variable functionality into a dedicated `customvar` (or `customvariable` etc.) module, would result in a self-explaining, more compact drop-down

![image](https://user-images.githubusercontent.com/84547391/154561065-423a8659-2364-4132-91b4-3cd1e3385a3e.png)

**Comment by abebeos** [comment]
The more I think about it, the more confident I get that "customvar" is an own module (though I understand your reluctance perfectly).

One could just start with duplicating the functionality within a customvar-module, to see what comes up. Assessing all this from scratch is difficult (at least for me).

**Comment by krocheck** [comment]
I think with the new structure we're working on for the Internal module we can setup additional 'built-in' modules.  In terms of upgrades, although we don't technically support moving actions/feedbacks between modules, the data points to modify for this are technically present and could be manipulated as such.  That would be difficult with a normal module because it would have to address the `shortid` of the new instance, but a built-in would be a hard key.

**Comment by abebeos** [comment]
This sounds good. Where can I file an issue re companions general internal/core design? Would this be https://github.com/bitfocus/companion or is it this repo here?

**Comment by krocheck** [comment]
We're not set up for it yet.  If you want to just start a repo in your account to get started that would be fine.

**Comment by Julusian** [comment]
Krocheck means starting a repo for making that new customvariables module.

Yes https://github.com/bitfocus/companion is the place for general things that arent related to a particular module. But be aware that we have started on a large refactoring and rewrite of a lot of the core application code for 2.3 already, with very little plan written down so now might not be the best time to look over the code. 
Also save yourself the pain of trying to understand the code flow for now, it is horrible to follow and is being made saner

**Comment by abebeos** [comment]
@Julusian , @krocheck & other team members.

I believe that at this point, it would help the core-team to get some feedback / 2nd opinions from a fresh pair of eyes.

Currently I'm just trying to isolate some tasks where I can assist you best, taking a time-frame of 3 months in account (till end of May). It looks like the `customvar` module would be a good entry point for me.

> Also save yourself the pain of trying to understand the code flow for now, it is horrible to follow and is being made saner

All good! After 30+ years with HW/SW, everything becomes easier, including "identifying the parts to stay away from".

**Comment by abebeos** [comment]
@Julusian , @krocheck , is it  currently possible (by design) to declare actions (accessible from UI) within `\companion\lib\variable.js?` Just curious.

**Comment by Julusian** [comment]
I think at some point it will be helpful, but I dont think right now is the time for it.
A lot of the code in the main repository and this predate my involvement in the project, so in some ways I am a fresh pair of eyes on it. I know there are many parts that confuse me in how/why they are like they are, but until now Ive been trying to avoid large unnecessary changes, knowing that this large rewrite was planned

The main objectives of the rewrite are to replace the prototype classes with proper classes, and to remove all the `system.emit` and `system.on` calls, and make them be normal method calls. Once this is completed, then we will try to evaluate the code flow and interactions between classes and improve it, but its very hard to get an overview on the interactions right now. So pretty much every line of the backend code is likely to be affected.
So you are welcome to have a look, but chances are you will mostly find things that we already intend to change as part of this work. But once this work has been done, I will be happy to get more eyes on it, and agree it would be useful to have

But yes, a `customvar` module would be a good place to start, making sure to do it in the modern class syntax, and avoiding any system.emit calls

**Comment by Julusian** [comment]
No, currently all actions are expected to come from modules. Again, this is something we will be changing as part of the refactoring, as all the sytem.emit and system.on calls made in the module will break and it will need to be adapted to use apis which we will not be exposing to normal modules

**Comment by abebeos** [comment]
> However, I would be open to dropping the `internal: ` prefix for actions/feedbacks from this module, and make them be added in the labels set in this repository.

This seems to be (for now) the best way to make the UI more self-explaining.

(other than that, no worries, I'll not start uncoordinated coding tasks for now, possibly just an smaller experimental one, or smaller 'mechanical' standard-stuff like #52)

**Comment by abebeos** [comment]
> and to remove all the `system.emit` and `system.on` calls

Assuming this is in order to make debugging/testing easier?

**Comment by abebeos** [comment]
You can find an early draft here:

**Comment by abebeos** [comment]
You can find an early draft here:

https://github.com/abebeos/companion-module-bitfocus-customvar

**Comment by abebeos** [comment]
This can't be fulfill with refactoring (Refactoring = zero functional change, quasi-mechanical processing). Thus changing title tag to `REWORK`

**Comment by abebeos** [comment]
@Julusian , @krocheck , I am at this point confident that this should be done independently of any ongoing redesign-work (3.0).

Of course I do not want to underrate/undermine your ongoing redesign efforts. But the existent 2.* code-line can be easily enhanced via carefull refactoring steps (real refactoring, quasi-mechanical non-breaking changes), each step leading to a better structure and more clarity, which in the end could help to fulfill the major redesign better/sooner.

I could just continue this, to provide you with a showcase, so you can see the benefits "live", but the effort is quite high.

So, me 99% confident: parallel refactoring of 2.*, and redesign of 3.0 should happen, to be prepared for everything that can come up - e.g. a (for whatever reasons) stucked 3.0.

**Comment by abebeos** [comment]
> However, I would be open to dropping the `internal: ` prefix for actions/feedbacks from this module, and make them be added in the labels set in this repository.

@Julusian , is this form of labeling currently available?

**Comment by abebeos** [comment]
> However, I would be open to dropping the `internal: ` prefix for actions/feedbacks from this module, and make them be added in the labels set in this repository.

closing, solved preliminary by using labels like `internal: CustomVar set Value`, see 501eade
