### ISSUE TITLE
Shell command to variable

### ISSUE THREAD

**Issue by chabad360** [bitfocus/companion-module-bitfocus-companion#61]
It would be nice if it were possible to save the stdout (or even stderr) to a custom variable. It could be used for feedback from a shell command (like showing cpu usage).

**Comment by JeffreyDavidsz** [comment]
I don't know if you already did, but please mention this on slack as we cannot see all changes. Thanks for your addition

**Comment by chabad360** [comment]
This is an issue again, it seems the change isn't included in the 2.3.0 betas

**Comment by JeffreyDavidsz** [comment]
Thanks for the reminder, the module is now in the core also
