### ISSUE TITLE
Select a Button Range for internal changes 

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion-module-bitfocus-companion#63]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Currently if you want to change say the background / Txt color of a lot of buttons you need to add in each button to an action. 

I would like to be able to select a range of buttons.  Page 1 Button 10 thru 32  = Background Red 

### Usecases

This could be used say once a button has been triggered it changes other buttons to red to "say" unavailable. I'm wanting to use this to make a button look disabled by changing the txt color to black.

**Comment by Julusian** [comment]
Bulk changes like this can be much easier handled by using a custom variable.

When pressed each button sets the custom-variable 'last-preset' to a unique identifier.
Each button also has a feedback which changes the style when the `last-preset` custom-variable matches their unique identifier.

I am open to this being possible if this is still wanted to be done explicitly
